---
- name: Uninstall Apache Web Server
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Stop and disable web server service
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: stopped
        enabled: no

    - name: Remove Apache package
      package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: absent

