---
- name: Install Apache Web Server
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install httpd on Amazon Linux / RHEL / CentOS
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install apache2 on Ubuntu / Debian
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure web server is started and enabled
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

