---
- name: Install and start Nginx on managed nodes
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx on RedHat/CentOS/Amazon Linux
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

